# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Uncaged"
license = "MIT"
licenselink = "https://github.com/jrutheiser/hugo-lithium-theme/blob/master/LICENSE.md"
description = "Forked from Lithium minimal theme by Jonathan Rutheiser"
homepage = "https://github.com/rdev0x1/uncaged-hugo-theme"
tags = ["blog"]
features = ["blog", "google analytics"]
min_version = 0.15

[author]
  name = "Ramon Dev"
  homepage = "https://rdev.pages.dev"

